export interface User {
  id: string,
  tgUsername?: string,
  tgId: string,
  email: string,
  isConfirmedEmail: boolean,
  tel: string,
  avatarUrl?: string,
  familyName: string,
  givenName: string,
  middleName: string,
  joinedDate: Date,
  level: number,

  canEditAchievements: boolean,
  canAssignAchievements: boolean,
  canEditRegistrations: boolean,
  canEditEvents: boolean,
  canEditUsersData: boolean,
  canEditDocs: boolean,
  canExecuteSQL: boolean,
  canEditHistory: boolean,

  isSignedIn: boolean,
}

export interface Event {
  id: string,
  title: string,
  description: string,
  routeDescription: string,
  createdDate: Date,
  startDate?: Date,
  cameDate?: Date,
  previewUrl?: boolean,
  customCSS?: string,
  lapDistanceKm: number,
  medalPreviewUrl: string,
  authorId: string,
  isYouRegistered: boolean,
  isYourRegistrationConfirmed?: boolean,
  yourComment?: string,
  registrationsCount: number,
}

export interface Registration {
  id: string,
  userId: string,
  eventId: string,
  isConfirmed?: boolean,
  userComment?: string,
  adminComment?: string,
  level?: number,
  salary?: number,
  taskText?: string,
  cameDate?: string,
  leaveDate?: Date,
  lapsPassed: number,
  userName: string,
  userTel: string,
  userTgUsername: string,
  userAvatarUrl: string,
}
